### PR TITLE
feat(setup): Add src folder

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Add the src folder to prepare for stuff

### CODE REVIEW

**Review by obostjancic — APPROVED** [review]
LGTM

**Comment by obostjancic** [comment]
Another comment here

**Review by obostjancic — CHANGES_REQUESTED** [review]
requesting changes foo bar baz

**Comment by obostjancic** [comment]
another comment

**Comment by ArthurKnaus** [comment]
Comment

**Comment by obostjancic** [comment]
another comment

**Review by obostjancic — CHANGES_REQUESTED** [review]
i need to leave a comment

**Comment by obostjancic** [comment]
commenting again

**Comment by obostjancic** [comment]
@ArthurKnaus hey

**Comment by obostjancic** [comment]
yooo

**Comment by obostjancic** [comment]
lfg

**Comment by obostjancic** [comment]
activity?

**Comment by obostjancic** [comment]
check this on github

**Comment by obostjancic** [comment]
begone

**Review by obostjancic — COMMENTED** [review]
lgtmmm

**Pull request closed without merging**
